### ISSUE TITLE
Error loading landing page on FF

### ISSUE THREAD

**Issue by thebeekeeper** [BillowLabs/teamkiosk#2]
Spinner never goes away, see this in the browser console:

14:57:07.206 "Error while processing route: dashboard" "t.some is not a function" "App.DashboardController<.updateBuilds/<@http://run00.com/index.js:1:8504
y@http://run00.com/libraries.js:21:12285
b@http://run00.com/libraries.js:21:12369
g@http://run00.com/libraries.js:21:12188
@http://run00.com/libraries.js:14:18727
r.prototype.invoke@http://run00.com/libraries.js:4:28876
r.prototype.flush@http://run00.com/libraries.js:4:29401
n.prototype.flush@http://run00.com/libraries.js:4:27552
a.prototype.end@http://run00.com/libraries.js:4:22751
o/e._autorun<@http://run00.com/libraries.js:4:21577
"1 libraries.js:13:9801
_() libraries.js:13
I.error() libraries.js:13
C() libraries.js:13
l() libraries.js:21
i.prototype.trigger() libraries.js:21
i/this.promise<() libraries.js:21
y() libraries.js:21
b() libraries.js:21
g() libraries.js:21
p() libraries.js:21
<anonymous> libraries.js:14
r.prototype.invoke() libraries.js:4
r.prototype.flush() libraries.js:4
n.prototype.flush() libraries.js:4
a.prototype.end() libraries.js:4
o/e._autorun<() libraries.js:4

**Comment by mhuensch** [comment]
Did you run using:
gulp --watch --data

The application only runs using faked data atm.

**Comment by thebeekeeper** [comment]
nope, i just went to the url!  i forgot you said it used local storage
